### ISSUE TITLE
Do not restrict the number of widgets per group

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [gisaia/ARLAS-wui-builder#184]
Instead of predefined widgets groups, allow to select the number of widgets, and for each widget let the user align it above a grid (6 columns should do the job).
In a group, each widget should also display the main information.

## EDIT
It is now possible to create as much widgets as we want. But there is no management of how to organise the widgets dispositions inside the group

**Comment by sebbousquet** [comment]
It's now possible to organise widgets in the group.
