### ISSUE TITLE
App review

### ISSUE THREAD

**Issue by WilliGautier** [gisaia/ARLAS-wui-builder#244]
Key is not working:
- [x] `Geographical field description` (in **Map**)
- [x] ~~`Id feature field description` (in **Map**)~~
- [x] `Metric collect function Description` (in **Analytics-Histogram**)
- [x] `Metric collect field Description` (in **Analytics-Histogram**)

Key is missing:
- [x] `Map` 
- [x] `Timeline`
- [x] `Search`
- [x] `Analytics`
- [x] `Side Modules`
- [x] `Look 'n feel`
- [x] `intersects` (in **Map**)
- [x] `notintersects` (in **Map**)
- [x] `notwithin` (in **Map**)
- [x] `within` (in **Map**)
- [x] `Saerch name descritpion` (wrong key, in **Search** )
- [x] ~~`Search a ...` (in **Search** )~~
- [x] `Choose aggreagation Mode` (wrong key, in **Timeline**)
- [x] `Features` (in **Map-Layers**)
- [x] `Features Metrics` (in **Map-Layers**)
- [x] `Cluster` (in **Map-Layers**)  
- [x] `Carreful! Warning, changing this field's value will reset some other fields`
- [x] `Fill` (in **Map-Layers**)
- [x] `Line` (in **Map-Layers**)
- [x] `Circle` (in **Map-Layers**)
- [x] `description` (in **Map-Layers-colors**) should be split
- [x] `Fix` (in **Map-Layers-colors**)
- [x] `Interpolated` (in **Map-Layers-colors**)
- [x] `Generated` (in **Map-Layers-colors**)
- [x] `Manual` (in **Map-Layers-colors**)
- [x] `Provided` (in **Map-Layers-colors**)
- [x] `Add keyword / color` (in **Map-Layers-colors**)
- [ ] `Data cell bbox description` (in **Map-Layers-aggregation**)
- [ ] `Data cell centroid description` (in **Map-Layers-aggregation**)
- [ ] `Cell center description` (in **Map-Layers-aggregation**)
- [ ] `Cell description` (in **Map-Layers-aggregation**)
- [x] ~~`New group` (in **Analytics**)~~
- [x] ~~`Swimlane` (in **Analytics**)~~
- [x] `Fixed height` (in **Analytics-Swimlane-rendered**)
- [x] `Variable height` (in **Analytics-Swimlane-rendered**)
- [x] `Circles` (in **Analytics-Swimlane-rendered**)

Key is used several times and make it annoying to describe:
- [x] `name` -> (`search name`, `Layer name` )
- [x] `Rendered geometry` -> (`Rendered geometry`, `Rendered geometry choice`)
- [x] `Geometry type description` -> (`Geometry type description for feature`, `Geometry type description for cluster`)
- [x] `Aggregation field` -> (`Temporal aggregation field`, `Geo aggregation field`, `Histogram aggregation field`, `Swimlane aggregation field`)
- [x] `Aggregation field description` -> (`Temporal aggregation field description`, `Geo aggregation field description`, `Histogram aggregation field description`, `Swimlane aggregation field description`)
- [x] `Field` -> ('Powerbar field`, `Cluster elected field`)
- [x] `Type` -> (`Aggregation type`, `Aggregation geometry`, `Widget type`)
- [x] `Size` -> (`Powerbar size`, `Donut size`)
- [ ] `Title` -> (`Metric title`)
- [x] `Metric` -> (`Metric`, `Swimlane metric`, `Histogram metric`)
- [x] `Rendered geometry` -> (`Layer rendered geometry`, `Layer geometry field`)

Key should be removed:
- [x] `Edit` is duplicated
- [x] `Title` is duplicated
- [ ] ...

RQ:
- [ ] Why not fusion `Features Metrics` and `Cluster` ?
- [ ] The description location of the layer color choice could be improve
- [ ] Move the map layer style geometry type to map layer geometry, rendered geometry (simplify the aggregation construction)
- [ ] In color choice in aggregated mode, `Count` should be one of the metrics (then simplify the interface)
- [ ] When choosing a field, K propose to group by type (string, numerical, geometry) in the list of proposed field, that's nice
- [x] When choosing a field, name are truncated, making it impossible to choose
- [x] In the histogram creation, the choice of aggregation metric is very strange. "Count" should be a normal metric collect function for user. (And the field choice should be in the same block). Same for Swimlane creation.
- [x] Bug: In Powerbar widget creation, the two tabs are called "Data" and you define the title two times.
- [x] Bug: in Resultlist widget creation, in rendered tab, there are two times the same param "Display filters"
- [ ] Color choice in swimlane is less customable than in other parts (donuts...)

**Comment by sebbousquet** [comment]
@WilliGautier I close this issue, create a new one if needed for your next review
