### ISSUE TITLE
App crash in analytics group creation when a widget is defined

### ISSUE THREAD

**Issue by WilliGautier** [gisaia/ARLAS-wui-builder#246]
In the Analytics configuration, I create a new tab.

In this tab, I create a group.

If I create a widget in this group, then the app crash when I try creating a new group, looking like this:

![image](https://user-images.githubusercontent.com/36915512/90615448-6d551980-e20c-11ea-88ad-d2fe6d9e51b0.png)

RQ: While you don't create widgets, you can add as many groups as you want correctly

**Comment by MohamedHamouGisaia** [comment]
Fixed #252
