### ISSUE TITLE
Error message in console on the start of the app

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-wui-builder#283]
In chrome
<img width="1097" alt="Capture d’écran 2020-10-02 à 11 02 32" src="https://user-images.githubusercontent.com/9316927/94906456-cae0b500-049e-11eb-9da6-228ed5ef152f.png">
In firefox 
<img width="633" alt="Capture d’écran 2020-10-02 à 11 03 23" src="https://user-images.githubusercontent.com/9316927/94906522-e9df4700-049e-11eb-8f13-ce56087ab779.png">

**Comment by sebbousquet** [comment]
Closed by #286
