### ISSUE TITLE
"Ajouter une couche de données" and "Ajouter un espace de visualisation" text is not wrapped inside the button

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui-builder#362]
when the window's width is less than 1516px
![image](https://user-images.githubusercontent.com/26741864/100380763-be4c8900-3017-11eb-99ed-54544e023938.png)

**Comment by mbarbet** [comment]
Same bug for "Ajouter un espace de visualisation"
