### ISSUE TITLE
Changing a max value in label size interpolation does not work

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui-builder#783]
- create a label layer (e.g. an arrow for the _water current orientation_)
- interpolate the size of the arrow by a metric (e.g. AVG on speed of the _water current_
- the WUI automatically sets the max value, then change it by hand
- save => it does not want to save. It does save if we do not overwrite the max value.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/35499583/181437570-fe82a6ef-e117-442a-a376-784342ed6ae8.png">

**Comment by sebbousquet** [comment]
@MohamedHamouGisaia @mbarbet 

After investigating:
The issue occurs when you change the min or max value of the label size in interpolation mode.

The `propertyInterpolatedValuesCtrl` control has a value of `null` which causes the form to be invalid.

When the user changes the max (or min) value the value of the `propertyInterpolatedValuesCtrl` control is set correctly, but its change state is triggered 3 times and the last time the value is set to `null`, I can't understand why.

Each changes is executed in the correct order and no one resets the value of `propertyInterpolatedValuesPreview` but if you log the value of this control in the `onDependencyChange` of the `propertyInterpolatedValuesPreview` control (the only control that has `propertyInterpolatedValuesPreview` as dependent control), you can see that the change is triggered 3 times:
<img width="269" alt="Capture d’écran 2022-08-26 à 14 56 49" src="https://user-images.githubusercontent.com/7236202/186908474-383c72e8-6d61-470c-a2ab-3e147e17ced1.png">

**Comment by MohamedHamouGisaia** [comment]
@sebbousquet 
The changes that were triggered 3 times were fixed earlier [here](https://github.com/gisaia/ARLAS-wui-builder/commit/2340c249a5dd20fd294f77a885a0b2c5353ddc3d#diff-ee0de716753a5ec360b264751cbe9a071869c99c94e96ba30b5c001e5a6df94bR609)
