### ISSUE TITLE
Impossible to save a configuration that has been downloaded

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui-builder#811]
With [this config](https://github.com/gisaia/ARLAS-wui-builder/files/9534570/config.zip), we obtain the following error when trying to save it after importing it.

![image](https://user-images.githubusercontent.com/104018401/189329873-bc8fc645-8379-44f2-9b77-98fde4636b01.png)

**Comment by MohamedHamouGisaia** [comment]
Viewed with @QuCMGisaia 
Not reproducible
Closing the issue
