### ISSUE TITLE
Listing collections to choose for the dashboard doesn't call the right organisation

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui-builder#889]
### How to reproduce
- I am mohamed.hamou@gisaia.com (user belonging to two orga: gisaia/toto)
- I choose the gisaia organization
- I edit an existing dashboard
- When I choose the collection, I can't find them
- This is due to a call to arlas-org-filter:toto instead of gisaia

**Comment by sebbousquet** [comment]
Fix by #890
