### ISSUE TITLE
Add more precision to the existing description of initial zoom selection

### ISSUE THREAD

**Issue by MAudelGisaia** [gisaia/ARLAS-wui-builder#918]
For the user, it can be difficult to know the meaning of the value ( ex : a zoom set to 7 is close to or outside the tile ?).

**Comment by QuCMGisaia** [comment]
For the minimum and maximum zoom of the visibility of the layers, information could also be added about what certain levels of zoom represent, as it is done in [mapbox's doc](https://docs.mapbox.com/help/glossary/zoom-level/)
